language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.7
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - raco pkg install --auto cover cover-codecov doc-coverage

install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR

script:
  - raco test -p db-connect
  - raco doc-coverage db/connect
  - raco cover -f codecov -d $TRAVIS_BUILD_DIR/coverage -p db-connect
